[server]
headless = true
enableCORS = false
port = 8501

[theme]
base = "dark"
primaryColor = "#00ffc3"
backgroundColor = "#0f0f0f"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#e0e0e0"
font = "sans serif"
